# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: song.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='song.proto',
  package='musicGrpc',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.examples.musicGrpcB\rMusicGrpcUserP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nsong.proto\x12\tmusicGrpc\"D\n\x08SongData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05\x61lbum\x18\x04 \x01(\t\"\x14\n\x06SongID\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xe4\x01\n\x04Song\x12\x35\n\x07\x41\x64\x64Song\x12\x13.musicGrpc.SongData\x1a\x13.musicGrpc.SongData\"\x00\x12\x38\n\nUpdateSong\x12\x13.musicGrpc.SongData\x1a\x13.musicGrpc.SongData\"\x00\x12\x33\n\x07GetSong\x12\x11.musicGrpc.SongID\x1a\x13.musicGrpc.SongData\"\x00\x12\x36\n\nRemoveSong\x12\x11.musicGrpc.SongID\x1a\x13.musicGrpc.SongData\"\x00\x42\x33\n\x1aio.grpc.examples.musicGrpcB\rMusicGrpcUserP\x01\xa2\x02\x03RTGb\x06proto3'
)




_SONGDATA = _descriptor.Descriptor(
  name='SongData',
  full_name='musicGrpc.SongData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='musicGrpc.SongData.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='musicGrpc.SongData.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='artist', full_name='musicGrpc.SongData.artist', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='album', full_name='musicGrpc.SongData.album', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=93,
)


_SONGID = _descriptor.Descriptor(
  name='SongID',
  full_name='musicGrpc.SongID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='musicGrpc.SongID.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['SongData'] = _SONGDATA
DESCRIPTOR.message_types_by_name['SongID'] = _SONGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SongData = _reflection.GeneratedProtocolMessageType('SongData', (_message.Message,), {
  'DESCRIPTOR' : _SONGDATA,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:musicGrpc.SongData)
  })
_sym_db.RegisterMessage(SongData)

SongID = _reflection.GeneratedProtocolMessageType('SongID', (_message.Message,), {
  'DESCRIPTOR' : _SONGID,
  '__module__' : 'song_pb2'
  # @@protoc_insertion_point(class_scope:musicGrpc.SongID)
  })
_sym_db.RegisterMessage(SongID)


DESCRIPTOR._options = None

_SONG = _descriptor.ServiceDescriptor(
  name='Song',
  full_name='musicGrpc.Song',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=346,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSong',
    full_name='musicGrpc.Song.AddSong',
    index=0,
    containing_service=None,
    input_type=_SONGDATA,
    output_type=_SONGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateSong',
    full_name='musicGrpc.Song.UpdateSong',
    index=1,
    containing_service=None,
    input_type=_SONGDATA,
    output_type=_SONGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSong',
    full_name='musicGrpc.Song.GetSong',
    index=2,
    containing_service=None,
    input_type=_SONGID,
    output_type=_SONGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveSong',
    full_name='musicGrpc.Song.RemoveSong',
    index=3,
    containing_service=None,
    input_type=_SONGID,
    output_type=_SONGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SONG)

DESCRIPTOR.services_by_name['Song'] = _SONG

# @@protoc_insertion_point(module_scope)
